package net.postchain.mc.cli.util

import com.chromia.cli.tools.config.ChromiaConfigOption
import com.chromia.cli.tools.env.cliEnv
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.groups.mutuallyExclusiveOptions
import com.github.ajalt.clikt.parameters.groups.required
import com.github.ajalt.clikt.parameters.groups.single
import com.github.ajalt.clikt.parameters.options.OptionTransformContext
import com.github.ajalt.clikt.parameters.options.convert
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.split
import com.github.ajalt.clikt.parameters.options.switch
import com.github.ajalt.clikt.parameters.options.validate
import com.github.ajalt.clikt.parameters.types.long
import com.github.ajalt.clikt.parameters.types.path
import net.postchain.chain0.model.ProviderQuotaType
import net.postchain.client.impl.PostchainClientImpl
import net.postchain.common.hexStringToByteArray
import net.postchain.crypto.PubKey
import net.postchain.mc.cli.base.CommandBase
import net.postchain.mc.cli.base.NAME_LENGTH_MAX
import net.postchain.rell.api.base.RellCliEnv
import java.net.MalformedURLException
import java.net.URISyntaxException
import java.net.URL


const val CHROMIA_CONFIG = "CHROMIA_CONFIG"
fun CliktCommand.pubkeyOption(helpMsg: String = "Public key") = option("-pk", "--pubkey", help = helpMsg, envvar = "POSTCHAIN_PUBKEY")
        .convert { PubKey(it) }

fun CliktCommand.pubkeysOption(helpMsg: String = "Comma delimited list of public keys") = option("--pubkeys", help = helpMsg)
        .convert { PubKey(it) }.split(",")

fun CliktCommand.pmcConfigOption() = PmcClientConfigOption(cliEnv())

class PmcClientConfigOption(cliEnv: RellCliEnv): ChromiaConfigOption(cliEnv) {
    val client by lazy { NopPostchainClient(PostchainClientImpl(config.get())) }
}

fun CliktCommand.nameOption(helpMessage: String) = option("-n", "--name", help = helpMessage)

fun CliktCommand.nameOrGenerateOption(helpMessage: String) = mutuallyExclusiveOptions(
        nameOption(helpMessage).validate(entityNameValidator()),
        option(
                "-a", "--auto-generate-name",
                help = "Set if ${helpMessage.lowercase()} should be autogenerated (suppressed by -n)"
        ).flag().convert {
            if (it) {
                CommandBase.autoGenerateName()
            } else null
        }
).single().required()

fun entityNameValidator(): OptionTransformContext.(String) -> Unit = {
    require(CommandBase.isEntityNameValid(it)) { "Name can only contain letters, numerals, and underscores. " }
    require(it.length <= NAME_LENGTH_MAX) { "Name is too long, maximum allowed length is $NAME_LENGTH_MAX" }
}

fun CliktCommand.urlOption(helpMessage: String) = option("--url", help = helpMessage)
        .validate(validateUrl())

fun validateUrl(): OptionTransformContext.(String) -> Unit = {
    val valid = try {
        URL(it).toURI()
        true
    } catch (e: MalformedURLException) {
        false
    } catch (e: URISyntaxException) {
        false
    }
    require(valid) { "Invalid URL provided: $it" }
}


sealed class VoterSetOrPubkeysOption(val data: String) {
    class Pubkeys(data: String) : VoterSetOrPubkeysOption(data) {
        val pubkeys get() = data.split(",").map { it.hexStringToByteArray() }
    }

    class VoterSet(data: String) : VoterSetOrPubkeysOption(data)

}

fun CliktCommand.pubkeysOrVotersetOption() = mutuallyExclusiveOptions(
        option("--voter-set", help = "Name of voter set").convert { VoterSetOrPubkeysOption.VoterSet(it) },
        option("--pubkeys", help = "Comma delimited list of public keys").convert { VoterSetOrPubkeysOption.Pubkeys(it) }
).single().required()

fun CliktCommand.maxBlockchainsOption() = option("-mb", "--max-blockchains", help = "Max number of blockchains per container").long()
fun CliktCommand.containerUnitsOption() = option("-cou", "--container-units", help = "Container Units (minimum 1)").long()
fun CliktCommand.clusterUnitsOption() = option("-clu", "--cluster-units", help = "Cluster Units (minimum 1)").long()

fun CliktCommand.providerTierOption() = option(help = "Provider tier").switch(
        "-cnp" to ProviderType.COMMUNITY_NODE_PROVIDER,
        "-np" to ProviderType.NODE_PROVIDER,
        "-sp" to ProviderType.SYSTEM_PROVIDER
)

fun CliktCommand.providerQuotaTypeOption() = option(help = "Provider quota type").switch(
        "-ma" to ProviderQuotaType.max_actions_per_day,
        "-mc" to ProviderQuotaType.max_containers,
        "-mn" to ProviderQuotaType.max_nodes
)

fun CliktCommand.proposalDescriptionOption(helpMessage: String = "Proposal description", default: String = "") = option("--description", help = helpMessage)
        .default(default)

fun CliktCommand.configurationsFileOption() = option("--configurations-file", help = "File to import blockchain configurations from")
        .path(mustExist = true, canBeDir = false, canBeFile = true, mustBeReadable = true)
