package net.postchain.mc.cli.util

import com.chromia.cli.tools.config.OptionalChromiaModelConfigOption
import com.chromia.cli.tools.env.cliEnv
import com.github.ajalt.clikt.core.CliktCommand
import com.github.ajalt.clikt.parameters.groups.mutuallyExclusiveOptions
import com.github.ajalt.clikt.parameters.groups.required
import com.github.ajalt.clikt.parameters.groups.single
import com.github.ajalt.clikt.parameters.options.OptionTransformContext
import com.github.ajalt.clikt.parameters.options.convert
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.flag
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.required
import com.github.ajalt.clikt.parameters.options.split
import com.github.ajalt.clikt.parameters.options.switch
import com.github.ajalt.clikt.parameters.options.validate
import com.github.ajalt.clikt.parameters.types.long
import com.github.ajalt.clikt.parameters.types.path
import net.postchain.chain0.model.ProviderQuotaType
import net.postchain.common.hexStringToByteArray
import net.postchain.crypto.PubKey
import net.postchain.mc.cli.base.CommandBase
import net.postchain.mc.cli.base.METADATA_LENGTH_MAX
import net.postchain.mc.cli.base.NAME_LENGTH_MAX
import net.postchain.mc.cli.base.URL_LENGTH_MAX
import net.postchain.rell.api.base.RellCliEnv
import java.net.MalformedURLException
import java.net.URISyntaxException
import java.net.URL


const val CHROMIA_CONFIG = "CHROMIA_CONFIG"
const val ECDSA_COMPRESSED_KEY_SIZE = 33
const val ECDSA_UNCOMPRESSED_KEY_SIZE = 65
const val DILITHIUM2_KEY_SIZE = 1336

fun CliktCommand.pubkeyOption(helpMsg: String = "Public key") = option("-pk", "--pubkey", help = helpMsg, envvar = "POSTCHAIN_PUBKEY")
        .convert { PubKey(it) }
        .required()
        .validate(pubkeyValidator())

fun CliktCommand.optionalPubkeyOption(helpMsg: String = "Public key") = option("-pk", "--pubkey", help = helpMsg, envvar = "POSTCHAIN_PUBKEY")
        .convert { PubKey(it) }
        .validate(pubkeyValidator())

fun CliktCommand.pubkeysOption(helpMsg: String = "Comma delimited list of public keys") = option("--pubkeys", help = helpMsg)
        .convert { PubKey(it) }.split(",")
        .required()
        .validate(pubkeysValidator())

fun pubkeyValidator(): OptionTransformContext.(PubKey) -> Unit = {
    validatePubkey(it)
}
fun pubkeysValidator(): OptionTransformContext.(List<PubKey>) -> Unit = {
    it.forEach(::validatePubkey)
}

fun OptionTransformContext.validatePubkey(pubKey: PubKey) {
    val keySize = pubKey.data.size
    require(keySize == ECDSA_COMPRESSED_KEY_SIZE || keySize == ECDSA_UNCOMPRESSED_KEY_SIZE || keySize == DILITHIUM2_KEY_SIZE) {
        "Size of public key $pubKey is not valid, must be $ECDSA_COMPRESSED_KEY_SIZE, $ECDSA_UNCOMPRESSED_KEY_SIZE or $DILITHIUM2_KEY_SIZE"
    }
}

fun CliktCommand.pmcConfigOption() = PmcClientConfigOption(cliEnv())

class PmcClientConfigOption(cliEnv: RellCliEnv) : OptionalChromiaModelConfigOption(cliEnv) {
    private val lookupBrid by option("--lookup-brid", help = "Ignore any 'brid' property in configuration file, always perform lookup").flag()
    val network by option("--network", help = "Target network to make requests to (if chromia.yml is configured)")
    val client by lazy {
        if (network != null) {
            requireNotNull(model) { "chromia.yml not found"}
            val networkModel = model!!.deployments[network]
                    ?: throw IllegalArgumentException("Network $network not found in configuration")
            config.setProperty("brid", networkModel.blockchainRid.toHex())
            config.setProperty("api.url", networkModel.urls.joinToString(","))
        }
        NopPostchainClient.withCachedBrid(config, lookupBrid)
    }

}

fun CliktCommand.nameOption(helpMessage: String) = option("-n", "--name", help = helpMessage)

fun CliktCommand.nameOrGenerateOption(helpMessage: String) = mutuallyExclusiveOptions(
        nameOption(helpMessage).validate(entityNameValidator()),
        option(
                "-a", "--auto-generate-name",
                help = "Set if ${helpMessage.lowercase()} should be autogenerated (suppressed by -n)"
        ).flag().convert {
            if (it) {
                CommandBase.autoGenerateName()
            } else null
        }
).single().required()

fun entityNameValidator(): OptionTransformContext.(String) -> Unit = {
    require(CommandBase.isEntityNameValid(it)) { "Name can only contain letters, numerals, and underscores. " }
    require(it.length <= NAME_LENGTH_MAX) { "Name is too long, maximum allowed length is $NAME_LENGTH_MAX" }
}

fun CliktCommand.requiredUrlOption(helpMessage: String, vararg names: String = arrayOf("--url")) = option(*names, help = helpMessage)
        .required()
        .validate(urlValidator())

fun CliktCommand.urlOption(helpMessage: String, vararg names: String = arrayOf("--url")) = option(*names, help = helpMessage)
        .validate(urlValidator())

fun urlValidator(): OptionTransformContext.(String) -> Unit = {
    validateUrl(it)
}

fun OptionTransformContext.validateUrl(url: String) {
    val valid = try {
        URL(url).toURI()
        true
    } catch (e: MalformedURLException) {
        false
    } catch (e: URISyntaxException) {
        false
    }
    require(valid) { "Invalid URL provided: $url" }
    require(url.length <= URL_LENGTH_MAX) { "URL is too long, maximum allowed length is $URL_LENGTH_MAX" }
}

fun metadataTextValidator(): OptionTransformContext.(String) -> Unit = {
    validateMetadataText(it)
}

fun OptionTransformContext.validateMetadataText(text: String) {
    require(text.length <= METADATA_LENGTH_MAX) { "value is too long, maximum allowed length is $METADATA_LENGTH_MAX" }
}

sealed class VoterSetOrPubkeysOption(val data: String) {
    class Pubkeys(data: String) : VoterSetOrPubkeysOption(data) {
        val pubkeys get() = data.split(",").map { it.hexStringToByteArray() }
    }

    class VoterSet(data: String) : VoterSetOrPubkeysOption(data)

}

fun CliktCommand.pubkeysOrVotersetOption() = mutuallyExclusiveOptions(
        option("--voter-set", help = "Name of voter set").convert { VoterSetOrPubkeysOption.VoterSet(it) },
        option("--pubkeys", help = "Comma delimited list of public keys").convert { VoterSetOrPubkeysOption.Pubkeys(it) }
).single().required()

fun CliktCommand.maxBlockchainsOption() = option("-mb", "--max-blockchains", help = "Max number of blockchains per container").long()
fun CliktCommand.containerUnitsOption() = option("-cou", "--container-units", help = "Container Units (minimum 1)").long()
fun CliktCommand.clusterUnitsOption() = option("-clu", "--cluster-units", help = "Cluster Units (minimum 1)").long()
fun CliktCommand.extraStorageOption() = option("-es", "--extra-storage", help = "Extra Storage (MiB)").long()

fun CliktCommand.providerTierOption() = option(help = "Provider tier").switch(
        "-cnp" to ProviderType.COMMUNITY_NODE_PROVIDER,
        "-np" to ProviderType.NODE_PROVIDER,
        "-sp" to ProviderType.SYSTEM_PROVIDER
)

fun CliktCommand.providerQuotaTypeOption() = option(help = "Provider quota type").switch(
        "-ma" to ProviderQuotaType.max_actions_per_day,
        "-mc" to ProviderQuotaType.max_containers,
        "-mn" to ProviderQuotaType.max_nodes
)

fun CliktCommand.proposalDescriptionOption(helpMessage: String = "Proposal description", default: String = "") = option("--description", help = helpMessage)
        .default(default)
        .validate(metadataTextValidator())

fun CliktCommand.configurationsFileOption() = option("--configurations-file", help = "File to import blockchain configurations from")
        .path(mustExist = true, canBeDir = false, canBeFile = true, mustBeReadable = true)
