package net.postchain.mc.cli.blockchain

import com.github.ajalt.clikt.parameters.groups.provideDelegate
import com.github.ajalt.clikt.parameters.options.required
import net.postchain.chain0.proposal_blockchain.getForcedConfigurationStage2Proposal
import net.postchain.gtv.GtvDecoder.decodeGtv
import net.postchain.gtv.GtvDictionary
import net.postchain.mc.cli.PmcCommand
import net.postchain.mc.cli.blockchainRidOption
import net.postchain.mc.cli.util.pmcConfigOption
import net.postchain.mc.gtv.diff.GtvDiffFinder
import net.postchain.mc.gtv.diff.GtvDiffFinder.pruneAutoGeneratedConfigFields
import net.postchain.mc.network.requireApiVersion

class CommandGetProposedForcedConfiguration : PmcCommand(
        name = "get-proposed-forced-configuration",
        help = "Get proposed forced configuration"
) {
    private val config by pmcConfigOption()
    private val client get() = config.client

    private val blockchainRID by blockchainRidOption().required()

    override fun run() {
        client.requireApiVersion(83)
        val p = client.getForcedConfigurationStage2Proposal(blockchainRID)
        if (p != null) {
            val currentConfig = pruneAutoGeneratedConfigFields(decodeGtv(p.currentConfiguration.data) as GtvDictionary)
            val newConfig = decodeGtv(p.proposedConfiguration.data) as GtvDictionary
            echo("Force for blockchain ${p.blockchainRid.toHex()} at height: ${p.proposedHeight}\n\n${GtvDiffFinder.diff(currentConfig, newConfig).diff}")
        } else {
            echo("No forced configuration for blockchain $blockchainRID")
        }
    }
}
