package net.postchain.mc.cli.blockchain

import com.github.ajalt.clikt.core.CliktError
import com.github.ajalt.clikt.parameters.groups.OptionGroup
import com.github.ajalt.clikt.parameters.groups.cooccurring
import com.github.ajalt.clikt.parameters.groups.provideDelegate
import com.github.ajalt.clikt.parameters.options.default
import com.github.ajalt.clikt.parameters.options.option
import com.github.ajalt.clikt.parameters.options.required
import com.github.ajalt.clikt.parameters.options.validate
import com.github.ajalt.clikt.parameters.types.file
import com.github.ajalt.clikt.parameters.types.long
import net.postchain.chain0.nm_api.nmFindPreviousConfigurationHeight
import net.postchain.chain0.nm_api.nmGetBlockchainConfiguration
import net.postchain.common.BlockchainRid
import net.postchain.gtv.Gtv
import net.postchain.gtv.GtvDecoder.decodeGtv
import net.postchain.gtv.GtvDictionary
import net.postchain.mc.cli.PmcCommand
import net.postchain.mc.cli.blockchainRidOption
import net.postchain.mc.cli.heightOption
import net.postchain.mc.cli.util.BlockchainConfig
import net.postchain.mc.cli.util.pmcConfigOption
import net.postchain.mc.gtv.diff.GtvDiffFinder
import net.postchain.mc.gtv.diff.GtvDiffFinder.pruneAutoGeneratedConfigFields
import net.postchain.mc.network.requireApiVersion

class FileOptions : OptionGroup() {
    val file1 by option("-bc1", "--blockchain-config-1", help = "Blockchain config 1 to diff")
            .file(mustExist = true, mustBeReadable = true, canBeDir = false).required()
    val file2 by option("-bc2", "--blockchain-config-2", help = "Blockchain config 2 to diff")
            .file(mustExist = true, mustBeReadable = true, canBeDir = false).required()
}

class BlockchainOptions : OptionGroup() {
    val blockchainRID by blockchainRidOption().required()
    val height by heightOption().default(Long.MAX_VALUE).validate {
        require(it > 0) { "--height must be > 0" }
    }
    val previousHeight by option("-ph", "--previous-height",
            help = "Configuration height to compare, use previous height by default").long().validate {
        require(it >= 0) { "--previous-height must be >= 0" }
    }
}

open class CommandBlockchainConfigurationDiff(
        name: String = "configuration-diff",
        help: String = "Blockchain configuration diff"
) : PmcCommand(
        name = name,
        help = help
) {
    private val config by pmcConfigOption()

    private val fileOptions by FileOptions().cooccurring()
    private val blockchainOptions by BlockchainOptions().cooccurring()

    override fun run() {
        config.client.requireApiVersion(64)

        val (config1, config2) = fileOptions?.let {
            echo("Diff between configuration in ${it.file1.name} and ${it.file2.name}:", err = true)
            BlockchainConfig.readFromFile(it.file1).gtv to BlockchainConfig.readFromFile(it.file2).gtv
        } ?: blockchainOptions?.let {
            fetchConfigs(it.blockchainRID, it.height, it.previousHeight)
        } ?: throw CliktError("Must specify either --blockchain-rid or --blockchain-config-1 and --blockchain-config-2")

        echo("", err = true)
        echo(GtvDiffFinder.diff(
                pruneAutoGeneratedConfigFields(config1 as GtvDictionary),
                pruneAutoGeneratedConfigFields(config2 as GtvDictionary)
        ).diff)
    }

    private fun fetchConfigs(blockchainRid: BlockchainRid, height: Long, previousHeight: Long?): Pair<Gtv, Gtv> {
        val currentHeight = config.client.nmFindPreviousConfigurationHeight(blockchainRid, if (height == Long.MAX_VALUE) height else height + 1)
                ?: throw CliktError("Cannot find blockchain configuration height")
        val currentConfig: Gtv = decodeGtv(config.client.nmGetBlockchainConfiguration(blockchainRid, currentHeight)
                ?: throw CliktError("Cannot find blockchain configuration"))

        val prevHeight = previousHeight
                ?: config.client.nmFindPreviousConfigurationHeight(blockchainRid, currentHeight)
                ?: throw CliktError("Cannot find previous blockchain configuration height")
        val prevConfig: Gtv = decodeGtv(config.client.nmGetBlockchainConfiguration(blockchainRid, prevHeight)
                ?: throw CliktError("Cannot find previous blockchain configuration"))

        echo("Diff between configuration at height $prevHeight and height $currentHeight:", err = true)

        return prevConfig to currentConfig
    }
}
