#!/bin/sh

set -eu

app_path=$0

while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

APP_HOME=$( cd "${APP_HOME:-./}.." && pwd -P ) || exit

JAR=$(find "$APP_HOME/lib" -maxdepth 1 -regex '.*/management-console-.[^/]*.jar')

RESOLVED_TMP_DIR=${TMPDIR-/tmp}
LOG_FOLDER="${RESOLVED_TMP_DIR%/}/chromia"

${RELL_JAVA:-java} ${JAVA_ARGS:-} -Duser.language=en -Duser.country=US -DCHR_LOG_FOLDER="$LOG_FOLDER" -cp "$JAR:$APP_HOME/lib/*" net.postchain.mc.Directory1Kt "$@"
